// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DiagFolderPath(arg1:string):Promise<string>;

export function FileExists(arg1:string,arg2:string):Promise<boolean>;

export function GetBase64Data(arg1:string):Promise<string>;

export function ListImages(arg1:string):Promise<Array<main.Image>>;
