// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFile(arg1, arg2) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DiagFolderPath(arg1) {
  return window['go']['main']['App']['DiagFolderPath'](arg1);
}

export function FileExists(arg1, arg2) {
  return window['go']['main']['App']['FileExists'](arg1, arg2);
}

export function GetBase64Data(arg1) {
  return window['go']['main']['App']['GetBase64Data'](arg1);
}

export function ListImages(arg1) {
  return window['go']['main']['App']['ListImages'](arg1);
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}
